import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSans.variable} o-grid !gap-y-0 font-sans antialiased`}
      >
        <section className="px-container-sm md:px-container-md col-span-full grid grid-cols-subgrid"></section>
        <Header className="bg-amber-200" />
        <main className="bg-amber-100 col-span-full grid grid-cols-subgrid">
          {children}
        </main>
        <Footer className="bg-amber-300" />
      </body>
    </html>
  );
}
